### ISSUE TITLE
GLIBC not found

### ISSUE THREAD

**Issue by rwwagner90** [davidwinter/electron-forge-maker-snap#32]
I am not sure what is happening here, but I am getting the following when trying to run my snap:

<img width="1304" alt="Screen_Shot_2021-02-09_at_2 04 42_PM" src="https://user-images.githubusercontent.com/2640861/107418115-47863e80-6ae4-11eb-8c5d-565e4414184f.png">

I opened an issue on the Snapcraft forums here https://forum.snapcraft.io/t/swach-0-7-1-will-not-launch/22652 and I've read that perhaps `snapcraft cleanbuild` will fix the issue?

Have you encountered anything like this before @davidwinter and do you have suggestions?

**Comment by davidwinter** [comment]
@rwwagner90 I've not noticed this issue before and was definitely able to run the `swach` snap previously when we were testing this package. Does it do anything differently if you just run `swach` rather than `snap run swach`?

**Comment by rwwagner90** [comment]
@davidwinter if I install the `.deb` version of Swach, everything runs fine, so it is something with snap that is causing issues. Yes I am using 0.7.1 of this package.

**Comment by rwwagner90** [comment]
Relevant issue in the snap forums is here https://forum.snapcraft.io/t/swach-0-7-1-will-not-launch/22652/4

**Comment by rwwagner90** [comment]
@davidwinter got a reply:

```
that seems to hardcode base: core18 in its snapcraft.yaml template … so you can only build snaps on an 18.04 system with this tool. creating your snaps on any other release with it will cause libc issues
```

So I think we need to perhaps update the `base`?

**Comment by davidwinter** [comment]
@rwwagner90 apologies for the delay! I've not been receiving GitHub notification emails on issues for some strange reason.

So this is likely because in the Snap YML file I'm currently using, it is using Ubuntu 18.04 as its base and GitHub actions now defaulting `ubuntu-latest` runner to 20.04. It was 18.04 before, and so that matched up.

In your GitHub actions workflow file, can you try pinning to `ubuntu-18.04` for now to see if that resolves the issue until I can figure out a change that will automatically switch between the two depending on what the CI server is running on?

**Comment by davidwinter** [comment]
See: https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/

**Comment by rwwagner90** [comment]
@davidwinter yeah, I can pin it. That does sound like the likely culprit.

**Comment by rwwagner90** [comment]
Pinning to Ubuntu 18 does fix this issue
